rpc_params:
  env_name: "highway-v0"
  device: "cuda"   # or "cpu"
  seed: 42

  num_train_steps: 50000
  learning_starts: 1000
  gamma: 0.99
  tau: 0.005

  env_buffer_size: 100000
  target_update_interval: 1
  log_interval: 1000
  save_snapshot_interval: 5000
  eval_episode_interval: 2000
  num_eval_episodes: 5

  latent_dims: 64
  model_hidden_dims: 256
  model_num_layers: 2
  kl_constraint: 0.1
  lambda_init: 1.0

  alpha_autotune: "true"
  alpha: 0.2

  noise_factor: 0.05
  batch_size: 64
  seq_len: 8
  lr: 0.0003

  video_dir: "videos"
  video_fps: 30
