_wandb:
    value:
        cli_version: 0.22.2
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
            "3":
                - 14
                - 16
            "4": 3.13.7
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
agent:
    value: RPC
alpha_autotune:
    value: true
alpha_init:
    value: 0.2
batch_size:
    value: 256
device:
    value: cuda
env_buffer_size:
    value: 1000000
env_name:
    value: Walker2d-v5
eval_episode_interval:
    value: 10000
gamma:
    value: 0.99
kl_constraint:
    value: 60
lambda_init:
    value: 1e-05
latent_dims:
    value: 16
learning_starts:
    value: 10000
log_interval:
    value: 500
lr:
    value: 0.0003
model_hidden_dims:
    value: 256
model_num_layers:
    value: 2
noise_factor:
    value: 2
num_eval_episodes:
    value: 5
num_train_steps:
    value: 1000000
record_eval:
    value: true
save_snapshot_interval:
    value: 10000
seed:
    value: 1
seq_len:
    value: 4
target_update_interval:
    value: 1
tau:
    value: 0.005
use_rpc:
    value: 1
video_dir:
    value: videos
video_fps:
    value: 30
